use_frameworks!

platform :ios, '10.0'

target 'DoraemonExtension_Example' do
  pod 'DoraemonExtension', :path => '../'

  target 'DoraemonExtension_Tests' do
    inherit! :search_paths

    
  end
end
